### PR TITLE
Kojix2 doc challenge

### PR DESCRIPTION
**Pull request by kojix2**
Draft pull request for discussion.

I do not expect this to be merged as is, but something is better than nothing.

@kou Please comment.

### CODE REVIEW

**Comment by kojix2** [comment]
gh-pages baranch: https://github.com/kojix2/ruby-gnome/tree/gh-pages
Deployed document: https://kojix2.github.io/ruby-gnome/

**Comment by kou** [comment]
Thanks!
I've merged this with some modifications.

**Comment by kou** [comment]
Deployed: http://ruby-gnome.github.io/ruby-gnome/doc/dev/

**Comment by kojix2** [comment]
Awesome!

**Pull request merged**
