### PR TITLE
GTK4: work around frozen and/or missing INVOKERS

### PR DESCRIPTION
**Pull request by HuBandiT**
Workaround to allow GTK4 to load despite some INVOKERS being frozen (Cairo::Context) or outright missing (Cairo::Surface).

Fixes the symptoms reported in #1455 but does not look at the actual cause, so it is not recommended for merging without further verification/investigation.

### CODE REVIEW

**Comment by kou** [comment]
Sorry for not working on this.
I'll update gdk4 and gtk4 with proper way.

**Comment by HuBandiT** [comment]
Your work honours us. Thank you in advance.

If there is documentation on the architecture, maybe some of us can help with small bits of work, now or in the future.

**Comment by HuBandiT** [comment]
... or if you can describe what needs to be done in this case.

**Comment by kou** [comment]
You're right. I should prepare documentation... But I don't like/good at writing documentation (in English)...

Idea: I can explain the architecture in Japanese verbally without pain. If someone listens the explanation in Japanese and writes documentation in English, I'm happy. :-) 

For this case, we need to re-prepare gdk4/gtk4 based on the latest gdk3/gtk3 because the current gdk4/gtk4 are based on old gdk3/gtk3 and we have many improvements in gdk4/gtk4 after the gdk4/gtk4 creations. I'm doing it for gdk4 for now.

**Comment by HuBandiT** [comment]
Sadly, I do not understand spoken Japanese. But I am reasonable in writing English technical text. So if you can explain in written Japanese (which I can try to understand using translation services), or in very basic English writing... and in code... then I (and others with time and skills to edit documentation but no knowledge of the architecture) can write better English documentation. A sharing of tasks/work: you give the information with minimal effort, others give good language (text editing).

**Comment by kou** [comment]
I found a person who can listen Japanese and write explained description to documentation in Japanese. We will try creating documentation a bit in this month. If we can create documentation, please translate it to English and brush up the translated documentation.

**Comment by HuBandiT** [comment]
That is exciting news! Yes, let's try! It will be difficult in the beginning. But I hope we can get something done. And if we share it publicly, I hope others will join in as well.

**Comment by kou** [comment]
Please try the current master.

**Comment by HuBandiT** [comment]
Thank you, it works now.

**Pull request closed without merging**
